language: ruby
services: docker
cache:
- bundler
before_install:
  - gem install -v 1.17.3 bundler --no-document
  - bundle _1.17.3_ install
install:
- bundle install
rvm:
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - alfonso.delgado@viamo.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-rabbitmq.gemspec
- gem install sensu-plugins-rabbitmq-*.gem
before_deploy:
- bash -c "[ ! -d bonsai/ ] && git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai || echo 'bonsai/ exists, skipping git clone'"
deploy:
- provider: script
  script: bonsai/ruby-runtime/travis-build-ruby-plugin-assets.sh sensu-rabbitmq
  skip_cleanup: true
  on:
    tags: true 
    all_branches: true
    rvm: 2.4.1
